version: '3.8'
services:
  database:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin12345
      POSTGRES_DB: hotel_reservation_db
    ports:
      - "5432:5432"
    networks:
      - hotel-net
    volumes:
      - pg-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - hotel-net

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - hotel-net
    volumes:
      - kafka-logs:/var/lib/kafka/logs

  app:
    build:
      context: .
    image: hotel-reservation
    ports:
      - "8989:8989"
    depends_on:
      - database
      - kafka
    networks:
      - hotel-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/hotel_reservation_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Admin12345
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

networks:
  hotel-net:
    driver: bridge

volumes:
  pg-data:
  kafka-logs:
